name: StelyTeam
author: Army_
version: "${project.version}"
main: fr.army.stelyteam.StelyTeamPlugin
api-version: "1.21"
depend:
  - "Vault"
  - "NoQueuePluginMessage"
  - "NBTAPI"
softdepend:
  - "Jobs"
  - "StelyClaim"
  - "WorldEdit"
  - "WorldGuard"
  - "BungeeChatConnect"
  - "Essentials"
  - "EssentialsChat"
commands:
  teamtchat:
    description: "Envoie un message dans le tchat de team"
    usage: "/teamtchat <message>"
    aliases: ["tt", "teamchat"]
  stelyteam:
    description: "Ouvre l'inventaire de team"
    usage: "/stelyteam"
    aliases: ["st"]
    home:
      description: "Se téléporter au home de team"
      usage: "/stelyteam home"
      aliases: ["h"]
    visual:
      description: "Renvoie une représentation du texte en couleur"
      usage: "/stelyteam visual <text>"
      aliases: ["v"]
    info:
      description: "Affiche les informations de la team"
      usage: "/stelyteam info <team>"
      aliases: ["i"]
    delete:
      description: "Supprime la team"
      usage: "/stelyteam delete <team>"
      aliases: ["del", "remove", "rm"]
      permissions:
        default: "op"
    money:
      description: "Affiche le solde de la team"
      usage: "/stelyteam money <team>"
      aliases: ["balance", "bal"]
      permissions:
        default: "op"
    claim:
      description: "Affiche si la team a débloqué le claim ou non"
      usage: "/stelyteam claim <team>"
      aliases: []
      permissions:
        default: "op"
    upgrade:
      description: "Améliore le nombre de membre max dans une team"
      usage: "/stelyteam upgrade <team>"
      aliases: ["up"]
      permissions:
        default: "op"
    downgrade:
      description: "Diminue le nombre de membre max dans une team"
      usage: "/stelyteam downgrade <team>"
      aliases: ["down"]
      permissions:
        default: "op"
    editname:
      description: "Change le nom d'une team"
      usage: "/stelyteam editname <team> <name>"
      permissions:
        default: "op"
    editprefix:
      description: "Change le préfixe d'une team"
      usage: "/stelyteam editprefix <team> <prefix>"
      permissions:
        default: "op"
    promote:
      description: "Promote un membre de la team"
      usage: "/stelyteam promote <team> <player>"
      permissions:
        default: "op"
    demote:
      description: "Demote un membre de la team"
      usage: "/stelyteam demote <team> <player>"
      permissions:
        default: "op"
    changeowner:
      description: "Change le gérant d'une team"
      usage: "/stelyteam changeowner <team> <player>"
      permissions:
        default: "op"
    addmember:
      description: "Ajoute un membre à la team"
      usage: "/stelyteam addmember <team> <player>"
      permissions:
        default: "op"
    removemember:
      description: "Enlève un membre de la team"
      usage: "/stelyteam removemember <team> <player>"
      permissions:
        default: "op"
    convertstorage:
      description: "Convertit les stockages de team vers le format NBT"
      usage: "/stelyteam convertstorage"
      permissions:
        default: "op"
